apiVersion: v1
kind: Service

metadata:
  name: app-service-mesh-svc
  namespace: app-mesh

spec:
  type: ClusterIP
  selector:
    app: app-service-mesh
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000  